# Generated by Django 4.1.3 on 2022-12-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multistep_form', '0002_remove_multistepform_cpwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multistepform',
            name='phno',
        ),
        migrations.RemoveField(
            model_name='multistepform',
            name='phno_2',
        ),
        migrations.RemoveField(
            model_name='multistepform',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='multistepform',
            name='pwd',
        ),
        migrations.RemoveField(
            model_name='multistepform',
            name='sign',
        ),
        migrations.RemoveField(
            model_name='multistepform',
            name='uname',
        ),
        migrations.AddField(
            model_name='multistepform',
            name='facebook',
            field=models.CharField(default='{Nothing Here}', max_length=255),
        ),
        migrations.AddField(
            model_name='multistepform',
            name='gplus',
            field=models.CharField(default='{Nothing Here}', max_length=255),
        ),
        migrations.AddField(
            model_name='multistepform',
            name='password',
            field=models.CharField(default='{Nothing Here}', max_length=255),
        ),
        migrations.AddField(
            model_name='multistepform',
            name='phone',
            field=models.CharField(default='{Nothing Here}', max_length=255),
        ),
        migrations.AddField(
            model_name='multistepform',
            name='twitter',
            field=models.CharField(default='{Nothing Here}', max_length=255),
        ),
        migrations.AlterField(
            model_name='multistepform',
            name='email',
            field=models.CharField(default='{Nothing Here}', max_length=255),
        ),
        migrations.AlterField(
            model_name='multistepform',
            name='fname',
            field=models.CharField(default='{Nothing Here}', max_length=255),
        ),
        migrations.AlterField(
            model_name='multistepform',
            name='lname',
            field=models.CharField(default='{Nothing Here}', max_length=255),
        ),
    ]
