# Generated by Django 4.1.3 on 2022-12-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multistep_form', '0003_remove_multistepform_phno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multistepform',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='multistepform',
            name='gplus',
        ),
        migrations.RemoveField(
            model_name='multistepform',
            name='password',
        ),
        migrations.RemoveField(
            model_name='multistepform',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='multistepform',
            name='twitter',
        ),
        migrations.AddField(
            model_name='multistepform',
            name='phno',
            field=models.CharField(default='{Nothing Here}', max_length=255),
        ),
        migrations.AddField(
            model_name='multistepform',
            name='phno_2',
            field=models.CharField(default='{Nothing Here}', max_length=255),
        ),
        migrations.AddField(
            model_name='multistepform',
            name='photo',
            field=models.FileField(default='images/default.jpeg', upload_to=''),
        ),
        migrations.AddField(
            model_name='multistepform',
            name='pwd',
            field=models.CharField(default='{Nothing Here}', max_length=255),
        ),
        migrations.AddField(
            model_name='multistepform',
            name='sign',
            field=models.FileField(default='images/default.jpeg', upload_to=''),
        ),
        migrations.AddField(
            model_name='multistepform',
            name='uname',
            field=models.CharField(default='{Nothing Here}', max_length=255),
        ),
    ]
