# Generated by Django 4.1.3 on 2022-12-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multistep_form', '0004_remove_multistepform_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistepform',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='multistepform',
            name='fname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='multistepform',
            name='lname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='multistepform',
            name='phno',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='multistepform',
            name='phno_2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='multistepform',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='multistepform',
            name='pwd',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='multistepform',
            name='sign',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='multistepform',
            name='uname',
            field=models.CharField(max_length=255),
        ),
    ]
